### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by eatyourpeas** [rcpch/digital-growth-charts-react-client#10]
https://github.com/rcpch/digital-growth-charts-react-client/blob/93a2ebdcacd56249c5e623067c7f2fd53f05ea7b/src/pages/Spreadsheet.js#L30-L30

**Comment by pacharanero** [comment]
I haven't seen any CORS errors myself - is this still a bug?
In the API management layer we've had to set a CORS policy to allow the API demo documentation to call another page - this has been done as per https://docs.microsoft.com/en-gb/azure/api-management/api-management-howto-developer-portal#cors

**Comment by eatyourpeas** [comment]
Closing.
