### ISSUE TITLE
Consider removing the Spreadsheet Upload link in the React client

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-react-client#20]
We only have that feature for some testing functions, and for use by @statist7 

We could leave the feature but remove the link to it, because I don't think we want to encourage Joe Public to be uploading spreadsheets and doing multiple calculations. Also I really don't want to encourage ANY more spreadsheet use in the NHS

**Comment by pacharanero** [comment]
Assigning @eatyourpeas to make the decision on whether to hide this feature since he built it

**Comment by eatyourpeas** [comment]
I agree.
Perhaps we could publish a Google sheets add-on for researchers capped at
certain number of calls.

**Comment by pacharanero** [comment]
Yes, that's a great idea. We wouldn't need to cap it in the SHeets add-on, the API would handle that. They would need a valid API key and the free tier is limited to 100 calls a week (at the moment - we haven't actually fully decided what fair limits should be)

**Comment by eatyourpeas** [comment]
This was implemented some time back.
