### ISSUE TITLE
Design Notes to work through.

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-react-client#24]
design notes from @kirsten-olson 
Demo site for growth charts - https://growth.rcpch.ac.uk/

## Design

- [x] Refer to attached guidance / KSS for colour/font use, etc. - can keep clean clear style but follow our forms approach (where feasible)

- [x] Add full logo at top, with banner style

- [x] Menu – can we display as on other RCPCH sites? (I for one keep missing it!)

- [x] We expect this may be used on mobile, so can do more checking – but it seems quite responsive, though wonder if menu / top links can display as burger menu

## Content/navigation

- [x] If possible, add home page to introduce what the site is for and who it is for, with a link to the data demo on a separate page (and on the menu / promoted from home page)

- [x] We need a clear redirection to RCPCH web pages for parents and carers looking for information about growth charts, especially if they are likely to land here from web searches; and/or to other growth charts information for families when available – suggest this be a block of copy on the home page

- [x] Check labels for data fields, as difficult (for us!) to read. For example, is top birth date, next date of measurement?

**Comment by eatyourpeas** [comment]
Many of these issues now nolonger relevant as the client will be ultimately embedded in the documentation.
