### ISSUE TITLE
Website footer

### ISSUE THREAD

**Issue by magdaumerska** [rcpch/digital-growth-charts-react-client#43]
- In the second column 'Support' - can Link Two connect with open forum? https://openhealthhub.org/c/rcpch-digital-growth-charts/47. The remaining links can be removed. 
- Can the third column be renamed to 'Contact us' and include the following: 'Email us on growth.digital@rcpch.ac.uk'. The remaining links can be removed. 
- Can the fourth column be renamed to 'About us' and include the following: 'The digital growth charts project is managed by the Royal College of Paediatrics and Child Health. Founded in 1996 and with members in the UK and internationally, we play a major role in postgraduate medical education, professional standards, research and policy'. Can it also include a link to RCPCH website https://www.rcpch.ac.uk/ ?

**Comment by pacharanero** [comment]
Thanks @magdaumerska this is perfect, I was puzzling over what those links should be!
I will update them. The changes will be visible in `unstable` first
