### ISSUE TITLE
Client currently allows measurements from multiple patients to be entered into one chart

### ISSUE THREAD

**Issue by chvanlennep** [rcpch/digital-growth-charts-react-client#57]
Client currently has no validation checking for measurements from multiple patients being entered into one chart.

Eg: it is possible to enter 2 measurements one after the other with different DOBs.

**Comment by eatyourpeas** [comment]
closed with commit https://github.com/rcpch/digital-growth-charts-react-client/commit/e31ff62cd0000de327448c1eb52c32e6cd30b508
