### ISSUE TITLE
Error message when pressing plus and minus icon button on Add Event

### ISSUE THREAD

**Issue by tommyyama2020** [rcpch/digital-growth-charts-react-client#89]
Can show the error message when this button is used. 
<img width="509" alt="Screenshot 2023-10-09 at 16 02 57" src="https://github.com/rcpch/digital-growth-charts-react-client/assets/38548157/8b82f6a3-a3bc-4804-9bc0-ae9fa3156b66">

**Comment by pacharanero** [comment]
Thanks @tommyyama2020 for reporting - do you have a screenshot of the error that is shown? Or copy/paste out of browser console?

Do you have more detailed repro instructions? When you say 'pressing plus and minus' is this in a specific order?

**Comment by eatyourpeas** [comment]
Thanks this does look to be a bug in the client.  I will look into it
Note you cannot enter an event and submit to the API without submitting a measurement also - this is because events must relate to a measurement.
Thanks for raising this.

**Comment by eatyourpeas** [comment]
Hi @pacharanero - I have pushed a fix for this issue to issue89 branch. If you have time could you please review and close if happy? If so, could you please bump the version as a patch?

**Comment by tommyyama2020** [comment]
hi, sorry to confuse you. It is an enhancement request. I am running the client on my local machine and thought its good to implement the error handling in plus and minus buttons on frontend side.  how this can be assigned to me?

**Comment by eatyourpeas** [comment]
@tommyyama2020 that is great thank you - we are very happy to have your help. Possibly the way to do this would be for @pacharanero  to review the outstanding PR and merge into this branch. From there you could clone the repo (which sounds like you have already done), make a branch for any suggestions you have and send in a pull request for me and @pacharanero to look at?
How does that sound?

**Comment by tommyyama2020** [comment]
Thanks a lot for a quick response and instruction. 
Sounds all good.  Once completed, will make a new branch and raise the PR at my convenience.    

`In addition , I kinda desperately looking for being connected with NHS doctors who may help us review the products  and would appreciate if you can introduce me to one of those you working with in the future.`🙂

**Comment by pacharanero** [comment]
@tommyyama2020 - I am an NHS doctor, as is @eatyourpeas, we may be able to help. When you refer to 'the products' are you meaning NHS Digital API products?

**Comment by tommyyama2020** [comment]
@pacharanero @eatyourpeas  Thanks a lot Doctor. Yes, I am going to start working on the onboarding process to access NHS Digital API prod and need clinical reviewers licensed in England down the road as you may know. 

My address is greenbox@icloud.com. Please let me reach out when I may need your help.  

Regards,

**Comment by pacharanero** [comment]
You will need to find a way to remunerate clinicians for the time spent on this work if you want it done properly. Perhaps you have already though t of this and have a plan. I mentione it only because too often it is assumed that because NHS doctors are free to go and see in the NHS GP surgery, their time is free for other things too. Any time away from clinical work is a loss of earnings.

**Comment by pacharanero** [comment]
@tommyyama2020 happy to discuss this further perhaps as Private Messages on the NHSD Developer Community site - I am @pacharanero on there as well.

For the purposes of this issue, it is closed by #90

**Comment by tommyyama2020** [comment]
@pacharanero  thanks a lot for sharing further. Doctor.  Yes,  I think that monetizing the product is one of important goals.  
Will reach out thr the dev community.

Also, I am happy to keep contributing/improving this brilliant digital growth chart.

**Comment by eatyourpeas** [comment]
That is great thanks @tommyyama2020
