### ISSUE TITLE
Upgrade Node version to 18 or higher

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-react-client#93]
Node 16 is now about to leave LTS status https://nodejs.dev/en/about/releases/
Se need to do an upgrade to use Node 18 or possibly even better Node 20, both of which are LTS editions
At the same time it is certain we will need to do updates of React and many of the dependencies, so that it works with the dGC React Component.

**Comment by tommyyama2020** [comment]
@pacharanero 
@dc2007git   @eatyourpeas 

Hope this finds you well. 
When `"@semantic-ui-react/craco-less"  is upgraded`from 1.xx to latest, it worked with `node `v20.10.0`, npm 10.2.3`.  If it looks okay, 
pls let me push appropriate changes at a later date. 

I guess that this is not a permanent solution, though

Thanks. 

<img width="479" alt="Screenshot 2023-12-25 at 16 32 41" src="https://github.com/rcpch/digital-growth-charts-react-client/assets/38548157/7f4e4a8f-3ba1-4e55-89a3-7b1590ed77b9">
<img width="681" alt="Screenshot 2023-12-25 at 16 29 38" src="https://github.com/rcpch/digital-growth-charts-react-client/assets/38548157/98bd5949-0c94-4972-941f-08720ec9452b">

**Comment by tommyyama2020** [comment]
@pacharanero 

https://github.com/rcpch/digital-growth-charts-react-client/assets/38548157/8a2c5776-9d4c-4e05-a18d-258e7837e3cf
