### ISSUE TITLE
Old branch - deletion candidate? `showcentilelabels`

### ISSUE THREAD

**Issue by pacharanero** [rcpch/digital-growth-charts-react-client#94]
https://github.com/rcpch/digital-growth-charts-react-client/tree/showcentilelabels
This branch has just one commit and implements a new prop. @eatyourpeas is this no longer needed?
Or is it work that needs to be merged in at some point?
(I am just tidying up old branches)

**Comment by dc2007git** [comment]
@eatyourpeas do you have any updates on this?

**Comment by dc2007git** [comment]
Deleted branch and closing comment as per PR #100
